name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]  # Every hour
  workflow_dispatch:
  push: {branches: ["main", "master"]}

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Core config
          user: soham-metha
          config_timezone: Asia/Calcutta
          committer_message: "update metrics"

          # Basic sections
          base: header, activity, community, repositories
          template: classic

          # Plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_introduction: yes
          plugin_habits: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_lines: yes
          plugin_activity: yes

          # Include org contributions
          plugin_repositories: yes
          plugin_repositories_affiliations: owner, collaborator, organization_member
