name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]  # Every hour
  workflow_dispatch:
  push: {branches: ["main", "master"]}

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Core config
          user: soham-metha
          config_timezone: Asia/Calcutta
          committer_message: "update metrics"

          config_theme: tokyonight
          config_border: yes
          config_border_radius: 12

          # Basic sections
          base: header, activity, community, repositories
          template: classic

          # Plugins
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent

          plugin_languages: yes

          plugin_introduction: yes

          plugin_habits_charts: yes

          plugin_followup: yes
          plugin_followup_sections: user

          plugin_lines: yes
          plugin_lines_sections: base,repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1

          plugin_activity: yes

          plugin_repositories: yes
          plugin_repositories_affiliations:  owner, collaborator
