name: Metrics
on:
    schedule: [{ cron: "0 * * * *" }] # Every hour
    workflow_dispatch:
    push: { branches: ["main", "master"] }

permissions:
    contents: write

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRICS_TOKEN }}

                  # Core config
                  user: soham-metha
                  config_timezone: Asia/Calcutta
                  committer_message: "update metrics"
                  config_output: svg
                  config_display: large
                  config_padding: 0, +40%
                  config_order: base.header, base.repositories, lines, followup, habits, activity, isocalendar

                  extras_css: |
                      .field svg {
                        fill: #58a6ff;
                      }
                      .field {
                        color: #36eeb1;
                      }
                      h1, h2, h3 {
                        color: #d2a8ff !important;
                      }
                      .added{
                        color:#56d364
                      }
                      .deleted{
                        color:#da3633
                      }
                      .label{
                        background-color:rgba(218,227,236,0.188);
                        color:#5ca8ff;
                        padding:0px 10px;
                        font-weight:500;
                        line-height:22px;
                        margin:2px 5px;
                        white-space:nowrap;
                        border-radius:32px;
                        font-size:12px
                      }
                      .dot{color:#2cbb5d;padding-right: 2px;}
                      .leetcode .intermediate .dot,
                      .leetcode .medium.gauge .gauge-arc{
                        color:#ffc01e;
                        padding-right: 2px;
                      }
                      .leetcode .advanced .dot,
                      .leetcode .hard.gauge .gauge-arc{
                        color:#ef4743;
                        padding-right: 2px;
                      }
                      .gauge{
                        stroke-linecap:round;
                        fill:none;
                        padding: 10px;
                      }
                      .gauge-base{
                        stroke:currentColor;
                        stroke-width:15
                      }
                      .gauge text{
                        font-size:38px;
                        font-weight:600
                      }
                      .gauge text.secondary{
                        font-size:23px
                      }
                      .leetcode .count{
                        font-size:10px;
                        color:#666;
                        padding-left: 3px;
                      }
                      .leetcode .infos .date{
                        font-size:10px;
                        color:#666;
                        padding-top: 5px;
                      }

                  extras_js: |
                      for (const {a, b} of [
                        {a:"#216e39", b:"#56d364"},  
                        {a:"#30a14e", b:"#36eeb1"}, 
                        {a:"#40c463", b:"#39c5cf"}, 
                        {a:"#9be9a8", b:"#ff7b72"},
                        {a:"#ebedf0", b:"#0d1117"},
                      ])
                      document.querySelectorAll(` [fill="${a}"]`).forEach(node => node.setAttribute("fill", b))

                  # Basic sections
                  base: header, repositories
                  template: classic

                  # Plugins
                  plugin_leetcode: no
                  plugin_leetcode_sections: solved, skills

                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: full-year

                  plugin_languages: no

                  plugin_introduction: no

                  plugin_habits: yes
                  plugin_habits_charts: yes
                  plugin_habits_charts_type: "graph"

                  #plugin_achievements: yes

                  plugin_followup: yes
                  plugin_followup_sections: user

                  plugin_lines: yes
                  plugin_lines_sections: base,repositories
                  plugin_lines_repositories_limit: 6
                  plugin_lines_delay: 30

                  plugin_activity: yes
                  plugin_languages_ignored: Mathematica, ShaderLab, C#

                  plugin_repositories: no
                  plugin_repositories_affiliations: owner, collaborator
                  plugin_repositories_featured: Soham-Metha/virex
                  repositories_skipped: Maxcastel10/Picto-game, Soham-Metha/Soham-Metha, Soham-Metha/Explorer
